PasswordManager/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('password_manager/', include(('password_manager_app.urls', 'password_manager_app'), namespace='password_manager')),

]

password_manager_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('entries/', views.EntryList.as_view(), name='entries'),
    path('details/<int:pk>', views.EntryDetail.as_view(), name='details'),
    path('add_entry/', views.EntryCreate.as_view(), name='add_entry'),
    path('edit_entry/<int:pk>', views.EntryEdit.as_view(), name='edit_entry'),
    path('delete_entry/<int:pk>', views.EntryDelete.as_view(), name='delete_entry'),

    path('register/', views.UserFormView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='login_form.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='password_manager:entries'), name='logout'),
]

password_manager_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Entry(models.Model):
    site_name = models.CharField(max_length=20)
    site_url = models.URLField()
    login_name = models.CharField(max_length=20)
    login_password = models.CharField(max_length=30)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.site_name

password_manager_app/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["username", 'email', 'password']

password_manager_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, ListView, CreateView, DeleteView, UpdateView, TemplateView
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login

from .models import Entry
from .forms import UserForm

# Create your views here.


class EntryList(ListView):
    model = Entry
    template_name = 'entry_list.html'

    def get_context_data(self, **kwargs):
        if not self.request.user.is_anonymous:
            context = super().get_context_data(**kwargs)
            context['entries'] = Entry.objects.filter(user=self.request.user)
            context['logged_user'] = self.request.user
            return context


class EntryDetail(TemplateView):
    template_name = 'details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        entry = Entry.objects.get(id=self.kwargs['pk'])
        context['entry'] = entry
        if not self.request.user.is_anonymous:
            context['user_is_logged'] = True
        return context


class EntryCreate(CreateView):
    model = Entry
    template_name = 'create.html'
    fields = ['site_name', 'site_url', 'login_name', 'login_password']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    success_url = reverse_lazy('password_manager:entries')



class EntryEdit(UpdateView):
    model = Entry
    template_name = 'edit.html'
    fields = ['site_name', 'site_url', 'login_name', 'login_password']

    def form_valid(self, form):
        return super().form_valid(form)

    success_url = reverse_lazy('password_manager:entries')


class EntryDelete(DeleteView):
    model = Entry
    template_name = 'confirm_delete.html'
    success_url = reverse_lazy('password_manager:entries')


class UserFormView(View):
    form_class = UserForm
    template_name = 'registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {"form": form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('password_manager:entries')

        return render(request, self.template_name, {'form': form})

password_manager_app/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">

  <title>{% block title %} Password Manager {% endblock %}</title>
  {% load staticfiles %}

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
  <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet" type="text/css">
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body class="base_color">
  <nav class="navbar navbar-inverse" >
    <div class="container-fluid">
        <!-- Logo -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"> </span>
                <span class="icon-bar"> </span>
                <span class="icon-bar"> </span>
            </button>
            <a href="{% url 'password_manager:entries' %}" class="navbar-brand">Password Manager</a>
        </div>

        <div class=" collapse navbar-collapse" id="#topNavBar">
            <!-- Menu -->
            <ul class="nav navbar-nav">
                <li> <a href= "{% url 'password_manager:login' %}">  <span class="glyphicon glyphicon-user"> </span> Log In</a> </li>
                <li> <a href= "{% url 'password_manager:register' %}">  <span class="glyphicon glyphicon-pencil"> </span> Register</a> </li>
            </ul>
            <!-- Add Buttons -->
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href= "{% url 'password_manager:logout' %}">
                        <span class="glyphicon glyphicon-off"> </span>&nbsp; Logout
                    </a>
                </li>

            </ul>
        </div>

    </div>
  </nav>
  {% block main_content %}
  {% endblock %}
</body>
</html>

password_manager_app/templates/confirm_delete.html
{% extends "base.html" %}

{% block main_content %}
<div style="text-align:center">
     <form action="" method="post">{% csrf_token %}
         <p><strong>Are you sure you want to delete this entry? </strong></p>
         <input type="submit" value="Confirm" class="btn btn-primary" />
         <a href= "{% url 'password_manager:entries' %}"><input type="button" value="No. Back to passwords list" class="btn btn-primary"/> </a>
     </form>
</div>
{% endblock %}

password_manager_app/templates/create.html
{% extends "base.html" %}

{% block main_content %}

<form action="" method="post" >{% csrf_token %}
    {% for field in form %}
        <div class="form-group" >
            <div class="col-sm-offset-2 col-sm-10">
                <span class="text-danger small"> {{ field.errors }}  </span>
            </div>
            <lable class="control-lable col-sm-2"> {{ field.label_tag }} </lable>
            <div class="col-sm-10"> {{ field }} </div>
        </div>
    {% endfor %}
    <input type="submit" value="Save" class="btn btn-primary"/>
    <a href= "{% url 'password_manager:entries' %}"><input type="button" value="Back to password list" class="btn btn-primary"/> </a>
</form>

{% endblock %}

password_manager_app/templates/details.html
{% extends "base.html" %}
{% block main_content %}

<div class="container">
    <h2> Details </h2>
    <a href="{% url 'password_manager:details' entry.id %}" class="btn btn-danger" target="_blank">Open in new window</a>
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th></th>
            </tr>

        </thead>
        <tbody>
                <tr>
                    <td> <b> Site name </b></td>
                    <td> <b> {{entry.site_name}} </b></td>
                </tr>
                <tr>
                    <td> <b> Site url </b></td>
                    <td><a href="{{ entry.site_url }}" target="_blank"> <b> {{entry.site_url}} </b></a></td>
                </tr>
                <tr>
                    <td> <b> Login name </b></td>
                    <td> <b> {{entry.login_name}} </b></td>
                </tr>
                <tr>
                    <td> <b> Login password </b></td>
                    <td> <b> {{entry.login_password}} </b></td>
                </tr>
        </tbody>
    </table>
    {% if user_is_logged %}
        <a href= "{% url 'password_manager:entries' %}"><input type="button" value="Back to password list" class="btn btn-primary"/> </a>
    {% endif %}
</div>

{% endblock %}

password_manager_app/templates/edit.html
{% extends "base.html" %}

{% block main_content %}

<form action="" method="post" >{% csrf_token %}
    {% for field in form %}
        <div class="form-group" >
            <div class="col-sm-offset-2 col-sm-10">
                <span class="text-danger small"> {{ field.errors }}  </span>
            </div>
            <lable class="control-lable col-sm-2"> {{ field.label_tag }} </lable>
            <div class="col-sm-10"> {{ field }} </div>
        </div>
    {% endfor %}
    <input type="submit" value="Edit" class="btn btn-primary"/>
    <a href= "{% url 'password_manager:entries' %}"><input type="button" value="Back to passwords list" class="btn btn-primary"/> </a>
</form>

{% endblock %}

password_manager_app/templates/entry_list.html
{% extends "base.html" %}
{% block main_content %}

{% if logged_user %}
    <h3>
        You are logged in as: {{ logged_user }}
    </h3>
    {% if entries %}
    <div class="container">
        <h2> <b>My passwords</b> <p class="glyphicon glyphicon-lock"></p> </h2>
        <h4><a href="{% url 'password_manager:add_entry' %}" class="btn btn-primary">Add Password</a></h4>
        <table class="table">
            <thead>
                <tr>
                    <th> Site Name </th>
                    <th> Login Name </th>
                </tr>
            </thead>
            <tbody>
                {% for entry in entries %}
                    <tr>
                        <td> {{entry.site_name}}</td>
                        <td> {{entry.login_name}}</td>
                        <td> <a style="color:black" href = "{% url 'password_manager:delete_entry' entry.id %}"> <span class= "glyphicon glyphicon-trash" ></span></a></td>
                        <td> <a style="color:black" href = "{% url 'password_manager:edit_entry' entry.id %}"> <span class= "glyphicon glyphicon-wrench" ></span> Edit</a></td>
                        <td> <a style="color:black" href = "{% url 'password_manager:details' entry.id %}"> <span class= "glyphicon glyphicon-expand" ></span> Details</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
        <p> No passwords to view, please add some </p>
        <a href="{% url 'password_manager:add_entry' %}" class="btn btn-primary">Add Password</a>
    {% endif %}

{% else %}
    <h3 style="text-align:center">Please log in</h3>
    <h3 style="text-align:center">If you don't have the account then register first</h3>
{% endif %}

{% endblock %}

password_manager_app/templates/login_form.html
{% extends "base.html" %}

{% block main_content %}

<h3> Please Log In </h3>
 <form action="" method="post">{% csrf_token %}
     {% for field in form %}
        <div class="form-group" >
            <div class="col-sm-offset-2 col-sm-10">
                <span class="text-danger small"> {{ field.errors }}  </span>
            </div>
            <lable class="control-lable col-sm-2"> {{ field.label_tag }} </lable>
            <div class="col-sm-10"> {{ field }} </div>
        </div>
     {% endfor %}
     <input type="submit" value="Log In" class="btn btn-primary"/>
 </form>
{% endblock %}

password_manager_app/templates/registration_form.html
{% extends "base.html" %}

{% block main_content %}


 <form action="" method="post">{% csrf_token %}
     {% for field in form %}
        <div class="form-group" >
            <div class="col-sm-offset-2 col-sm-10">
                <span class="text-danger small"> {{ field.errors }}  </span>
            </div>
            <lable class="control-lable col-sm-2"> {{ field.label_tag }} </lable>
            <div class="col-sm-10"> {{ field }} </div>
        </div>
     {% endfor %}
     <input type="submit" value="Save" class="btn btn-primary"/>
 </form>
{% endblock %}